import Providers from "@/context/Providers";
import "@/styles/main.scss";

export const metadata = {
  title: "Limi Ecommerce",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning >
      <body >
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
